### ISSUE TITLE
JSON-RPC 2.0 implementation is not completed

### ISSUE THREAD

**Issue by hidehalo** [1ma/JsonRpc#4]
Hi:
I review the codes about [`Request`](https://github.com/1ma/JsonRpc/blob/master/src/Request.php)&[`Reseponse`](https://github.com/1ma/JsonRpc/blob/master/src/Response.php), I found it not totally implement all feature of JSON-RPC 2.0, I means parse and build req/batch_req/res etc.
I hope you could check [`it`](https://github.com/hidehalo/json-rpc/tree/master/src/Protocol), it's a implementation of JSON-RPC 2.0. If you think it's helpful, I consider to make a new PR for this repository.

**Comment by 1ma** [comment]
Hi, thanks for your input!

What parts of the spec do you mean, more specifically? Keep in mind that in this library the end user is not supposed to build the Request object himself. The Server takes care of parsing the incoming string and turn it into a Request or a series of Requests (when it's a batch request). IOW the user only needs to think about processing single requests, but the library also supports batch requests transparently.

**Comment by hidehalo** [comment]
> Keep in mind that in this library the end user is not supposed to build the Request object himself. 

sorry,I am missing the `Success`/`Error`/`Input` etc before last comment, those implementations is simple and good for user, I also think it's not flexible enough for users which want to expand their custom server(eg: add `stub`/`network component`/`name service` etc), cause end user only could care about procedure logic.
