### ISSUE TITLE
Missing possibility to add custom Formats, Filter and Media types to Json validation

### ISSUE THREAD

**Issue by FTI-Herbert** [1ma/JsonRpc#9]
It is not possible to add custom Formats, Filters and Media types to Json validation.
This makes it impossible to extend it in the moment:
```
if ($procedure->getSpec() instanceof stdClass && !Validator::validate($procedure->getSpec(), $request->params())) {
            return static::end(Error::invalidParams($request->id()), $request);
        }
```

```
 public static function validate(stdClass $schema, $data): bool
    {
        \assert(false !== \json_encode($data));
        return (new OpisValidator)
            ->dataValidation($data, $schema)
            ->isValid();
    }
```

A possible solution will be to extend the "Procedure" interface and add the FormatContainer FilterContainer and the MediTypeContainer to the Validator.
```
if ($procedure->getSpec() instanceof stdClass && !Validator::validate(
$procedure->getSpec(),
$procedure->getFormats(),
$procedure->getFilters(),
$procedure->getMedias(), 
$request->params())) {
            return static::end(Error::invalidParams($request->id()), $request);
        }
```
Or use the Procedure object for validate.  

```
if ($procedure->getSpec() instanceof stdClass && !Validator::validate($procedure, $request->params())) {
            return static::end(Error::invalidParams($request->id()), $request);
        }
```

**Comment by 1ma** [comment]
Yes, this is on purpose. The [JSON-RPC 2.0 spec](https://www.jsonrpc.org/specification) is rather strict about the response format, error codes and whatnot (see [section 5.1](https://www.jsonrpc.org/specification#error_object)), and my aim with the library is to follow the spec as close as possible. This in turn helps a lot with testing, for instance [EndToEndTest](https://github.com/1ma/JsonRpc/blob/ad794800ce7d1b7ba2b63a0870d8878f1e40f571/tests/Functional/EndToEndTest.php#L43) basically tries all the examples from section 7 in PHPUnit format.

Keep in mind though that the code you referenced is to handle a kind of "internal" error that the framework can detect itself before calling user procedures (`-32602 invalid params` in this case). Apart from these you can instantiate and return the `Error` class directly from your procedures and make up any kind of error you need, like [in this example](https://github.com/1ma/JsonRpc/blob/ad794800ce7d1b7ba2b63a0870d8878f1e40f571/tests/Unit/ErrorTest.php#L51) from the test suite. Despite this the final response will still follow the JSON-RPC 2.0 format.

Regarding custom medias ([I understand you mean this?](https://en.wikipedia.org/wiki/Media_type)), also keep in mind that the JSON-RPC 2.0 spec is decoupled from HTTP, and this is an HTTP concern. This means that HTTP methods, paths, headers and the like can't be part of the library. If you want to return a specific `Content-Type` header in the HTTP response you should handle this outside the scope of this library (e.g. in a Symfony controller).

**Comment by FTI-Herbert** [comment]
For my point of view this will not change the response Error. As you recommend we want to validate the request with a json schema. In the spec of the json schema you can define custom formats for types. E.G a Date format for string type. The OpisValidaror supports these feature, but the implementation makes in impossible to use this.

**Comment by 1ma** [comment]
Addressed in #10 

@FTI-Herbert do you need opis/json-schema 1.0 or are you happy with 2.0? I had some breaking changes sitting on master so I cannot tag 3.1.0, I have to go for 4.0.0.

I'd like to take this chance to bump several minimum versions of the dependencies, including Opis. But if you need Opis 1.0 I can leave the version bumping for a later 5.0.0.

**Comment by FTI-Herbert** [comment]
@1ma i'm totaly happy with 2.0

**Comment by FTI-Herbert** [comment]
@1ma i know this does not belong to this issue, but i want to implement the open-rpc method "rpc.discover". It would be very helpfull if i can get the methods out of the server object. So is it possible to implement getMethods() into the server?

**Comment by 1ma** [comment]
Sure. Open a new PR and we'll hash it out.
